// <auto-generated />
using CampusMediaBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusMediaBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260131195403_AddUserProfileTable")]
    partial class AddUserProfileTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CampusMediaBack.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Department 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Department 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Department 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Department 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Department 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Department 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Department 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Department 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Department 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Department 10"
                        });
                });

            modelBuilder.Entity("CampusMediaBack.Models.Pedagogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Courses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.PrimitiveCollection<string>("ResearchAreas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Pedagogues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Courses = "[]",
                            Department = "Department 2",
                            Name = "PedagogueName1",
                            Rating = 4.0999999999999996,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname1",
                            University = "University 2",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 2,
                            Courses = "[]",
                            Department = "Department 3",
                            Name = "PedagogueName2",
                            Rating = 4.2000000000000002,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname2",
                            University = "University 3",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 3,
                            Courses = "[]",
                            Department = "Department 4",
                            Name = "PedagogueName3",
                            Rating = 4.2999999999999998,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname3",
                            University = "University 4",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 4,
                            Courses = "[]",
                            Department = "Department 5",
                            Name = "PedagogueName4",
                            Rating = 4.4000000000000004,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname4",
                            University = "University 5",
                            YearsOfExperience = 9
                        },
                        new
                        {
                            Id = 5,
                            Courses = "[]",
                            Department = "Department 6",
                            Name = "PedagogueName5",
                            Rating = 4.5,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname5",
                            University = "University 6",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 6,
                            Courses = "[]",
                            Department = "Department 7",
                            Name = "PedagogueName6",
                            Rating = 4.5999999999999996,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname6",
                            University = "University 7",
                            YearsOfExperience = 11
                        },
                        new
                        {
                            Id = 7,
                            Courses = "[]",
                            Department = "Department 8",
                            Name = "PedagogueName7",
                            Rating = 4.7000000000000002,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname7",
                            University = "University 8",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 8,
                            Courses = "[]",
                            Department = "Department 9",
                            Name = "PedagogueName8",
                            Rating = 4.7999999999999998,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname8",
                            University = "University 9",
                            YearsOfExperience = 13
                        },
                        new
                        {
                            Id = 9,
                            Courses = "[]",
                            Department = "Department 10",
                            Name = "PedagogueName9",
                            Rating = 4.9000000000000004,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname9",
                            University = "University 10",
                            YearsOfExperience = 14
                        },
                        new
                        {
                            Id = 10,
                            Courses = "[]",
                            Department = "Department 1",
                            Name = "PedagogueName10",
                            Rating = 5.0,
                            ResearchAreas = "[]",
                            Surname = "PedagogueSurname10",
                            University = "University 1",
                            YearsOfExperience = 15
                        });
                });

            modelBuilder.Entity("CampusMediaBack.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("Likes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Post Caption 1",
                            Date = "2026-01-30",
                            Image = "https://picsum.photos/seed/post1/200/300",
                            Likes = "[]",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Post Caption 2",
                            Date = "2026-01-29",
                            Image = "https://picsum.photos/seed/post2/200/300",
                            Likes = "[]",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Post Caption 3",
                            Date = "2026-01-28",
                            Image = "https://picsum.photos/seed/post3/200/300",
                            Likes = "[]",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Post Caption 4",
                            Date = "2026-01-27",
                            Image = "https://picsum.photos/seed/post4/200/300",
                            Likes = "[]",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Caption = "Post Caption 5",
                            Date = "2026-01-26",
                            Image = "https://picsum.photos/seed/post5/200/300",
                            Likes = "[]",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Caption = "Post Caption 6",
                            Date = "2026-01-25",
                            Image = "https://picsum.photos/seed/post6/200/300",
                            Likes = "[]",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Caption = "Post Caption 7",
                            Date = "2026-01-24",
                            Image = "https://picsum.photos/seed/post7/200/300",
                            Likes = "[]",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Caption = "Post Caption 8",
                            Date = "2026-01-23",
                            Image = "https://picsum.photos/seed/post8/200/300",
                            Likes = "[]",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Caption = "Post Caption 9",
                            Date = "2026-01-22",
                            Image = "https://picsum.photos/seed/post9/200/300",
                            Likes = "[]",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Caption = "Post Caption 10",
                            Date = "2026-01-21",
                            Image = "https://picsum.photos/seed/post10/200/300",
                            Likes = "[]",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("CampusMediaBack.Models.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Department 2",
                            Name = "Program 1",
                            Rating = 4.0999999999999996,
                            Type = "Bachelor"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Department 3",
                            Name = "Program 2",
                            Rating = 4.2000000000000002,
                            Type = "Master"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Department 4",
                            Name = "Program 3",
                            Rating = 4.2999999999999998,
                            Type = "PhD"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Department 5",
                            Name = "Program 4",
                            Rating = 4.4000000000000004,
                            Type = "Master"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Department 6",
                            Name = "Program 5",
                            Rating = 4.5,
                            Type = "Bachelor"
                        },
                        new
                        {
                            Id = 6,
                            Department = "Department 7",
                            Name = "Program 6",
                            Rating = 4.5999999999999996,
                            Type = "PhD"
                        },
                        new
                        {
                            Id = 7,
                            Department = "Department 8",
                            Name = "Program 7",
                            Rating = 4.7000000000000002,
                            Type = "Bachelor"
                        },
                        new
                        {
                            Id = 8,
                            Department = "Department 9",
                            Name = "Program 8",
                            Rating = 4.7999999999999998,
                            Type = "Master"
                        },
                        new
                        {
                            Id = 9,
                            Department = "Department 10",
                            Name = "Program 9",
                            Rating = 4.9000000000000004,
                            Type = "PhD"
                        },
                        new
                        {
                            Id = 10,
                            Department = "Department 1",
                            Name = "Program 10",
                            Rating = 5.0,
                            Type = "Master"
                        });
                });

            modelBuilder.Entity("CampusMediaBack.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Comment = "Review Comment 1",
                            Date = "2026-01-30",
                            ReviewerId = "1",
                            Score = 4,
                            TargetId = 1,
                            TargetType = "prof"
                        },
                        new
                        {
                            Id = "2",
                            Comment = "Review Comment 2",
                            Date = "2026-01-29",
                            ReviewerId = "2",
                            Score = 5,
                            TargetId = 2,
                            TargetType = "uni"
                        },
                        new
                        {
                            Id = "3",
                            Comment = "Review Comment 3",
                            Date = "2026-01-28",
                            ReviewerId = "3",
                            Score = 3,
                            TargetId = 3,
                            TargetType = "prof"
                        },
                        new
                        {
                            Id = "4",
                            Comment = "Review Comment 4",
                            Date = "2026-01-27",
                            ReviewerId = "4",
                            Score = 4,
                            TargetId = 4,
                            TargetType = "uni"
                        },
                        new
                        {
                            Id = "5",
                            Comment = "Review Comment 5",
                            Date = "2026-01-26",
                            ReviewerId = "5",
                            Score = 5,
                            TargetId = 5,
                            TargetType = "prof"
                        },
                        new
                        {
                            Id = "6",
                            Comment = "Review Comment 6",
                            Date = "2026-01-25",
                            ReviewerId = "6",
                            Score = 3,
                            TargetId = 6,
                            TargetType = "uni"
                        },
                        new
                        {
                            Id = "7",
                            Comment = "Review Comment 7",
                            Date = "2026-01-24",
                            ReviewerId = "7",
                            Score = 4,
                            TargetId = 7,
                            TargetType = "prof"
                        },
                        new
                        {
                            Id = "8",
                            Comment = "Review Comment 8",
                            Date = "2026-01-23",
                            ReviewerId = "8",
                            Score = 5,
                            TargetId = 8,
                            TargetType = "uni"
                        },
                        new
                        {
                            Id = "9",
                            Comment = "Review Comment 9",
                            Date = "2026-01-22",
                            ReviewerId = "9",
                            Score = 3,
                            TargetId = 9,
                            TargetType = "prof"
                        },
                        new
                        {
                            Id = "10",
                            Comment = "Review Comment 10",
                            Date = "2026-01-21",
                            ReviewerId = "10",
                            Score = 4,
                            TargetId = 10,
                            TargetType = "uni"
                        });
                });

            modelBuilder.Entity("CampusMediaBack.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("ViewedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://picsum.photos/seed/story1/200/300",
                            UserId = 1,
                            Username = "User 1",
                            ViewedBy = "[]"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://picsum.photos/seed/story2/200/300",
                            UserId = 2,
                            Username = "User 2",
                            ViewedBy = "[]"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://picsum.photos/seed/story3/200/300",
                            UserId = 3,
                            Username = "User 3",
                            ViewedBy = "[]"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://picsum.photos/seed/story4/200/300",
                            UserId = 4,
                            Username = "User 4",
                            ViewedBy = "[]"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://picsum.photos/seed/story5/200/300",
                            UserId = 5,
                            Username = "User 5",
                            ViewedBy = "[]"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://picsum.photos/seed/story6/200/300",
                            UserId = 6,
                            Username = "User 6",
                            ViewedBy = "[]"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://picsum.photos/seed/story7/200/300",
                            UserId = 7,
                            Username = "User 7",
                            ViewedBy = "[]"
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://picsum.photos/seed/story8/200/300",
                            UserId = 8,
                            Username = "User 8",
                            ViewedBy = "[]"
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://picsum.photos/seed/story9/200/300",
                            UserId = 9,
                            Username = "User 9",
                            ViewedBy = "[]"
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://picsum.photos/seed/story10/200/300",
                            UserId = 10,
                            Username = "User 10",
                            ViewedBy = "[]"
                        });
                });

            modelBuilder.Entity("CampusMediaBack.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aliases = "[]",
                            Name = "University 1",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 2,
                            Aliases = "[]",
                            Name = "University 2",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Aliases = "[]",
                            Name = "University 3",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Aliases = "[]",
                            Name = "University 4",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 5,
                            Aliases = "[]",
                            Name = "University 5",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 6,
                            Aliases = "[]",
                            Name = "University 6",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 7,
                            Aliases = "[]",
                            Name = "University 7",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 8,
                            Aliases = "[]",
                            Name = "University 8",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 9,
                            Aliases = "[]",
                            Name = "University 9",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 10,
                            Aliases = "[]",
                            Name = "University 10",
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("CampusMediaBack.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("Friends")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Department 2",
                            Email = "user1@example.com",
                            Friends = "[]",
                            Name = "User 1",
                            PasswordHash = "$2a$11$tRDE1aHMiWcylZDXFGxmpeNTuZlcOMc.Lp9wGZhlvth76NzJIoycy",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user1",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 2"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Department 3",
                            Email = "user2@example.com",
                            Friends = "[]",
                            Name = "User 2",
                            PasswordHash = "$2a$11$biF6k9Zwh/oMji74ox/nfeUTfbkWGESTAlGTGPpTmza89e/UOCDKa",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user2",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 3"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Department 4",
                            Email = "user3@example.com",
                            Friends = "[]",
                            Name = "User 3",
                            PasswordHash = "$2a$11$UelBhJeGkTjFfXcqx5Mn7eiKBPvyjGGKQPBiz6pRZLSIXMovuw6XS",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user3",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 4"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Department 5",
                            Email = "user4@example.com",
                            Friends = "[]",
                            Name = "User 4",
                            PasswordHash = "$2a$11$0XGejjEN1ZRYKYvRKVWAdecYpDZgW8g7tzZLAaehPds1zKeC81FdC",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user4",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 5"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Department 6",
                            Email = "user5@example.com",
                            Friends = "[]",
                            Name = "User 5",
                            PasswordHash = "$2a$11$ViUNHCtor6zU5WzFsPHoWe9.6LM7QEe9fJtUxvYk5d/Hpc9tL5asK",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user5",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 6"
                        },
                        new
                        {
                            Id = 6,
                            Department = "Department 7",
                            Email = "user6@example.com",
                            Friends = "[]",
                            Name = "User 6",
                            PasswordHash = "$2a$11$VuOeKP4geOYeCdk4fA0CCeidmIZo24tn7OJ4lvT.fTvLxJ8rhX2MK",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user6",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 7"
                        },
                        new
                        {
                            Id = 7,
                            Department = "Department 8",
                            Email = "user7@example.com",
                            Friends = "[]",
                            Name = "User 7",
                            PasswordHash = "$2a$11$BnZQOSX3saqguj1sR5P1.ePAkyiKcYtGQp9Q2D1vjd1JTZUxiwVj.",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user7",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 8"
                        },
                        new
                        {
                            Id = 8,
                            Department = "Department 9",
                            Email = "user8@example.com",
                            Friends = "[]",
                            Name = "User 8",
                            PasswordHash = "$2a$11$N0JNH8CaubH0JRYoT7bkQeITh0TlD3FDOG002UAFAdqTmAKl2WEMO",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user8",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 9"
                        },
                        new
                        {
                            Id = 9,
                            Department = "Department 10",
                            Email = "user9@example.com",
                            Friends = "[]",
                            Name = "User 9",
                            PasswordHash = "$2a$11$nE7uD37ycat.aEewlDcls.5/UwluElB4OZZ1Zicd1jp39Cl9LmSyK",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user9",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 10"
                        },
                        new
                        {
                            Id = 10,
                            Department = "Department 1",
                            Email = "user10@example.com",
                            Friends = "[]",
                            Name = "User 10",
                            PasswordHash = "$2a$11$ht1rfMwmhxYZzwUAMIt2p.UFyLHg82Ub0V0ic2QJNinBzosCCgwiC",
                            ProfileImage = "https://api.dicebear.com/7.x/avataaars/svg?seed=user10",
                            Role = "student",
                            Suggestions = "[]",
                            University = "University 1"
                        });
                });

            modelBuilder.Entity("CampusMediaBack.Models.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("CampusMediaBack.Models.Department", b =>
                {
                    b.HasOne("CampusMediaBack.Models.University", null)
                        .WithMany("Departments")
                        .HasForeignKey("UniversityId");
                });

            modelBuilder.Entity("CampusMediaBack.Models.Pedagogue", b =>
                {
                    b.HasOne("CampusMediaBack.Models.Department", null)
                        .WithMany("Professors")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("CampusMediaBack.Models.Post", b =>
                {
                    b.HasOne("CampusMediaBack.Models.User", null)
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampusMediaBack.Models.Program", b =>
                {
                    b.HasOne("CampusMediaBack.Models.Department", null)
                        .WithMany("Programs")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("CampusMediaBack.Models.Story", b =>
                {
                    b.HasOne("CampusMediaBack.Models.User", null)
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampusMediaBack.Models.UserProfile", b =>
                {
                    b.HasOne("CampusMediaBack.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("CampusMediaBack.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusMediaBack.Models.Department", b =>
                {
                    b.Navigation("Professors");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("CampusMediaBack.Models.University", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("CampusMediaBack.Models.User", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
